algorithm: 'carefl'

data:
  seed: 0

# Flow model parameters
flow:
  architecture: 'CL'
  net_class: 'MLP4'
  nl: 5            # Number of flow layers
  nh: 32           # Number of hidden units
  batch_norm: false
  prior_dist: 'gaussian'
  scale: false     # Whether to use scaling in affine transformations
  shift_base: true

training:
  epochs: 1000
  seed: 0
  batch_size: 256
  patience: 50
  min_epochs: 100
  early_stopping_threshold: 0.0005

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.005
  beta1: 0.9
  amsgrad: false
  scheduler: true


